"""empty message

Revision ID: 33d7dc879442
Revises: 6cacd2577567
Create Date: 2021-09-02 13:41:47.496737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d7dc879442'
down_revision = '6cacd2577567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booksCompleted', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('booksCompleted')

    # ### end Alembic commands ###
