"""attribute rename in Collections

Revision ID: 84a01327faa9
Revises: 54e1e42a3618
Create Date: 2021-10-05 11:40:09.847911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a01327faa9'
down_revision = '54e1e42a3618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itemsCompleted', sa.Text(), nullable=True))
        batch_op.drop_column('booksCompleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booksCompleted', sa.TEXT(), nullable=True))
        batch_op.drop_column('itemsCompleted')

    # ### end Alembic commands ###
