"""empty message

Revision ID: 8d77c3f6dc58
Revises: 33d7dc879442
Create Date: 2021-09-02 13:50:36.007227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d77c3f6dc58'
down_revision = '33d7dc879442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booksCompleted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('booksCompleted')

    # ### end Alembic commands ###
